# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: '6f9cdff3-a6b9-47e1-90a8-6590ba11e157@1'
  inputs:
    jsonFile: '$(Build.Repository.LocalPath)/projects/ng-porcelain/package.json'
    shouldPrefixVariables: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Tagging Porcelain $PORCELAIN_VERSION"
      git tag $PORCELAIN_VERSION
      git push --tags origin -c http.extraheader="Authorization: Bearer $ACCESS_TOKEN"
  env:
    PORCELAIN_VERSION: 'v$(json.version)'
    ACCESS_TOKEN: $(System.AccessToken)

- script: |
    npm install
    npx ng build ngPorcelain
  displayName: 'npm install and build'

- script: echo $(Build.Repository.LocalPath) && pwd
  displayName: Print Workspace and pwd



- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.Repository.LocalPath)/dist/ng-porcelain'
    artifact: 'ng-porcelain--$(json.version)'

