# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# https://github.com/jeffpriz/vsts-json-to-variable/blob/master/Json2Variable/task.json
- task: OneLuckiDev.json2variable.vsts-json-to-variable.oneLuckiDevJson2Variable@1
  displayName: 'Load Variables'
  inputs:
    jsonFile: '$(Build.Repository.LocalPath)/projects/ng-porcelain/package.json'
    shouldPrefixVariables: false

- script: |
    npm install
    npm run create-package
  displayName: 'create bundle'

- script: echo $(Build.Repository.LocalPath) && pwd
  displayName: Print Workspace and pwd

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.Repository.LocalPath)/dist/ng-porcelain'
    artifact: 'ng-porcelain'

## this relies on permissions given to the service account
## https://ultfs.visualstudio.com/myUL/_settings/repositories?repositoryId=f2aa6adb-0529-4cfb-83f3-ef8537742fb3&_a=security
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Tagging Porcelain $PORCELAIN_VERSION"
      git tag $PORCELAIN_VERSION
      git -c http.extraheader="Authorization: Bearer $ACCESS_TOKEN" push --tags origin 
  env:
    PORCELAIN_VERSION: 'v$(json.version)'
    ACCESS_TOKEN: $(System.AccessToken)