# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git fetch origin
    git remote add github https://github.com/my-ul/ng-porcelain.git
    git push github --all

  displayName: 'Add GitHub remote and push'
